name: WebView Update
on:
  release:
    types: [published]
  workflow_dispatch: 
  repository_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 도구 설치
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk wget unzip

      - name: Android SDK 설치
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip -O tools.zip
          mkdir -p $HOME/android-sdk/cmdline-tools
          unzip tools.zip -d $HOME/android-sdk/cmdline-tools/latest
          rm tools.zip
          echo "export ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV

      - name: SDK 및 플랫폼 설치
        run: |
          source $GITHUB_ENV
          yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools" "platforms;android-30" "build-tools;30.0.3"
          yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT "extras;google;m2repository" "extras;android;m2repository"

      - name: 해독
        run: |
          source $GITHUB_ENV
          sdkmanager --install "platforms;android-30" # Ensure platform is installed before using apktool
          apktool if $ANDROID_SDK_ROOT/platforms/android-30/android.jar
          wget https://github.com/uazo/cromite/releases/download/latest/arm64_SystemWebView64.apk -O input.apk
          apktool d input.apk -o decompiled

      - name: 매니페스트 수정
        run: |
          sed -i 's/package="com.android.webview"/package="com.google.android.webview"/' decompiled/AndroidManifest.xml
          sed -i 's/android:exported="false"/android:exported="true"/g' decompiled/AndroidManifest.xml
          sed -i 's/android:exported=""/android:exported="true"/g' decompiled/AndroidManifest.xml

      - name: 재구성
        run: |
          apktool b decompiled -o output.apk

      - name: 키설정
        run: |
          if [ ! -f key.jks ]; then
            keytool -genkey -v -keystore key.jks -alias keyalias -keyalg RSA -keysize 2048 -validity 10000 -storepass mypassword -keypass mypassword -dname "CN=User, OU=Unit, O=Org, L=City, ST=State, C=Country"
          fi

      - name: 서명
        run: |
          apksigner sign --ks key.jks --out signed.apk output.apk

      - name: 업로드
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: signed.apk
