name: WebView Update

on:
  release:
    types: [published]
  workflow_dispatch: 
  repository_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 다운
        run: |
          wget https://github.com/uazo/cromite/releases/latest/download/arm64_SystemWebView64.apk -O input.apk

      - name: 도구 설치
        run: |
          sudo apt-get update
          sudo apt-get install -y apktool openjdk-11-jdk

      - name: 프레임워크 리소스 설치
        run: |
          apktool if /usr/share/apktool/framework/1.apk

      - name: 해독
        run: apktool d input.apk -o decompiled

      - name: 매니페스트 수정
        run: |
          sed -i 's/package="com.android.webview"/package="com.google.android.webview"/' decompiled/AndroidManifest.xml
          sed -i 's/android:exported="false"/android:exported="true"/g' decompiled/AndroidManifest.xml
          sed -i 's/android:exported=""/android:exported="true"/g' decompiled/AndroidManifest.xml

      - name: 재구성
        run: apktool b decompiled -o output.apk

      - name: 서명
        run: apksigner sign --ks key.jks --out signed.apk output.apk

      - name: 업로드
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: signed.apk
